experiment_type: benchmark

cp:
  epsilon_range: [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
  risk_tolerant:
    distance: Linf
    p: 1
    aggregation: weighted_average
    beta: 10
    norm_fun:
      sigmoid:
        k: 1
        shift: 0
  knn:
    K: 5
    min_samples: 0
  

model:
  train_model: true
  model_name: dt_model_max50
  ruleset_file: dt_rules_max50.csv
  max_n_rules: 50
  ccp_alpha: 0
  min_samples_thr: 0.15

output:
  res_dir: results/paper_ieee_synthetic_n50_min15perc
  save_plots: false


synthetic_dataset:
  generate_data: false
  n_clusters_per_class: 2
  n_features: 2
  n_points: 5000
  outputlabel: output
  cls0label: 0
  cls1label: 1

  save_data: true
  plot_epsilon: 0.05

  scenarios:
    easy:
      centers:
        - [0, 0]
        - [4, 0]
        - [0, 4]
        - [4, 4]
      sigmas: [0.4, 0.4, 0.4, 0.4]

    medium:
      centers:
        - [0, 0]
        - [3, 1]
        - [1.5, 4]
        - [5, 3]
      sigmas: [0.6, 0.8, 0.7, 0.9]

    hard:
      centers:
        - [0, 0]
        - [2, 0.5]
        - [1.5, 2]
        - [3, 2.5]
      sigmas: [1.0, 1.2, 1.0, 1.4]

    very_hard:
      centers:
        - [0, 2]
        - [2, 0]
        - [-2, 0]
        - [0, -2]
      sigmas: [0.9, 0.9, 0.9, 0.9]

    very_very_hard:
      centers:
        - [0, 0]
        - [1.2, 0.3]
        - [-0.8, 1.0]
        - [0.5, -1.1]
      sigmas: [1.2, 1.0, 1.3, 1.1]
  

dataset:
  data_path: data/ 

